### ISSUE TITLE
readme-checker plugin is case sensitive

### ISSUE THREAD

**Issue by abedurftig** [freenowtech/sauron#48]
The readme-checker plugin will check for the existence of a "README.md" file and ignore any files which are not strictly following convention.

Actual Behaviour:

- Project with "README.md" will be flagged as `missingOrEmptyReadme = false`
- Project with "readme.md" will be flagged as `missingOrEmptyReadme = true`

Expected Behaviour:

- Project with "README.md" will be flagged as `missingOrEmptyReadme = false`
- Project with "readme.md" will be flagged as `missingOrEmptyReadme = false`

**Comment by sergioasantiago** [comment]
Hey @abedurftig thank you for your feedback. I agree with the purposed change. If you feel comfortable, feel free to create a PR with this change, otherwise I will tackle whenever I have some free time.

**Comment by sergioasantiago** [comment]
Yes indeed. Just ping me if you have issues.
